# Generated by Django 4.1.1 on 2022-09-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=104)),
                ('salary', models.FloatField(db_column='nb_salary')),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
