# Generated by Django 4.1.1 on 2022-09-21 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, db_column='id_department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.departament'),
        ),
    ]
