# Generated by Django 4.1.1 on 2022-09-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('0', 'Masculine'), ('1', 'Feminine')], db_column='cs_sex', default=0, max_length=1, verbose_name='sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(db_column='nb_salary', decimal_places=2, max_digits=10),
        ),
    ]
